### ISSUE TITLE
landscape PDF

### ISSUE THREAD

**Issue by BobCashStory** [jmaupetit/md2pdf#33]
how can we generate a pdf in landscape mode ?

**Comment by jmaupetit** [comment]
By using a custom CSS file with the following media query:

```css
@media print{
  @page {
    size: landscape
  }
}
```

HTH
